---
all:
  children:
    doet_icap:
      hosts:
        doet-gropicap01-prod:
          ansible_host: 10.128.40.31
        doet-gropicap02-prod:
          ansible_host: 10.128.40.32
        doet-gropicap03-prod:
          ansible_host: 10.128.40.33
        doet-gropicap04-prod:
          ansible_host: 10.128.40.34
