---
all:
  children:
    doet_icap:
      hosts:
        doet-gropicap01-prod:
          ansible_host: 10.130.100.191   # eth1 - external / internet-facing NIC
        doet-gropicap02-prod:
          ansible_host: 10.130.100.192
        doet-gropicap03-prod:
          ansible_host: 10.130.100.193
        doet-gropicap04-prod:
          ansible_host: 10.130.100.194
